apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        #image: 431147460194.dkr.ecr.us-east-2.amazonaws.com/springboot:latest
        #image: image-registry.openshift-image-registry.svc:5000/openshift/springboot:latest
        image: gcr.io/fair-sandbox-366108/springboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-svc
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
